services:
  - type: web
    name: ovnivers
    env: node
    runtime: node
    buildCommand: npm install --no-audit --no-fund
    startCommand: node --max-old-space-size=400 server.js
    plan: free
    healthCheckPath: /health
    autoDeploy: true
